### ISSUE TITLE
Support for interrogation with Object Group60

### ISSUE THREAD

**Issue by lizapolyudova** [stepfunc/dnp3#130]
Hello,

I am working on an outstation implementation using the stepfunc.io DNP3 library and getting to the point of testing with the third party. Up to this point I've been testing with a slightly modified `master_tcp_client.rs` sample code provided in the example folder, which works fine.

The master we are integrating with; however, does not seem to poll for data in the same way. Specifically, here's their phrasing:

```
[the master will] interrogate each [outstation] with DNP3 Object 60
```

I am not entirely sure what would be the correct way to configure the outstation to accommodate for that and whether it's possible.

Below are some things I've tried:

I've enabled verbose logging at: 
* Application
* Link
* Transport

Master address in this case is 101.
Outstation address is 1.

layers, and getting the following:

```
LINK TX - ControlField { func: PriUnconfirmedUserData, master: false, fcb: false, fcv: false } source: 1 destination: 101 payload: 7 bytes C1 FB 82 80 00 03 A1
--
TRANSPORT TX - FIN: true FIR: true SEQ: 1 length: 4 FB 82 80 00
APP TX - ctrl: [fir: true fin: true con: true uns: true seq: 11] func: UnsolicitedResponse iin1: [DEVICE_RESTART] iin2: [] ... (len = 0)
LINK TX - ControlField { func: PriUnconfirmedUserData, master: false, fcb: false, fcv: false } source: 1 destination: 101 payload: 7 bytes C0 FA 82 80 00 ED 40
TRANSPORT TX - FIN: true FIR: true SEQ: 0 length: 4 FA 82 80 00
APP TX - ctrl: [fir: true fin: true con: true uns: true seq: 10] func: UnsolicitedResponse iin1: [DEVICE_RESTART] iin2: [] ... (len = 0)
```

My read of this is:  outstation is sending an unsolicited response to master, since (**UnsolicitedResponse** and **source: 1 destination: 101**)

I am having a somewhat hard time figuring out how to:

* read the logs to get a sense of what data is being sent to the outstation. 
* configure my testing setup to simulate interrogation via Object Group60Var2 

Thank you for your help and all your hard work writing this library!

**Comment by lizapolyudova** [comment]
err my bad. I am seeing the sample master code issue g60v2 reads.
I think the issue might be that the client has two separate masters which both attempt to poll from the same outstation, which results in TCP thrashing (connections keep closing before the outstation is able to return any data)

**Comment by emgre** [comment]
- Interrogation via Group60v2 means the master is polling for Class 1 events. You can modify line 83 of `master_tcp_master` example with `EventClasses::new(true, false, false)` to periodically send g60v2 polls.
- For cleaner logs, disable link-layer and transport layer, as they are rarely useful. Only print the app-level with full decoding.
- What you are seeing in these logs is the initial unsolicited null response. It doesn't contain any data and is mainly used to notify a master that the outstation restarted.
- I think you might want to disable unsolicited responses as the requirements given to you suggest that only polling will be used.
- You cannot have two masters communicating with the same outstation instance. DNP3 is a stateful protocol so it doesn't make sense to share the state across two masters. If you want to expose the same data to two masters, you need to create two outstations and keep both of them updated with the same data. The "TCP thrashing" you are experiencing is our library trying to keep only one connection alive per-channel.

Please be advised that although the source code is available publicly, using this library in a commercial manner requires a license. More details are available here: https://docs.stepfunc.io/dnp3/0.9.1/guide/docs/license

**Comment by lizapolyudova** [comment]
Thank you for the detailed response! 

> You cannot have two masters communicating with the same outstation instance. DNP3 is a stateful protocol so it doesn't make sense to share the state across two masters. If you want to expose the same data to two masters, you need to create two outstations and keep both of them updated with the same data. The "TCP thrashing" you are experiencing is our library trying to keep only one connection alive per-channel.

Yes, my next iteration was to create two outstations. I will be talking to the third party that runs the master to see if they could provide us with static IPs for each of the masters (otherwise, it seems like the two outstations have a conflict, since they are not able to distinguish which connection should go to which outstation).

Is there a reason traffic cannot be redirected based on the DNP master address? (I'm guessing because the DNP3 packet isn't actually interpreted until it gets to an outstation). 

So it seems like either static IPs would be the best bet; or, possibly reading the contents of the client certificate and forwarding traffic to the correct instance 

> Please be advised that although the source code is available publicly, using this library in a commercial manner requires a license. More details are available here:

Yes, thank you! We are just past the development process and fairly certain that we are going ahead to production with this code, so will definitely be purchasing a commercial license.

**Comment by emgre** [comment]
> Yes, my next iteration was to create two outstations. I will be talking to the third party that runs the master to see if they could provide us with static IPs for each of the masters (otherwise, it seems like the two outstations have a conflict, since they are not able to distinguish which connection should go to which outstation).
> 
> Is there a reason traffic cannot be redirected based on the DNP master address? (I'm guessing because the DNP3 packet isn't actually interpreted until it gets to an outstation).

When the server is binded, we get connections and we can either accept them or drop them based on their IP address. We haven't parsed anything yet. That's where the filtering occurs. The DNP3 link-layer address is something that is generally used in multi-drop scenarios on serial (i.e. one master communicating with multiple outstations sharing the same wire).

In your situation, you can either have two outstations on a single `TcpServer` and masters with static IPs that you filter (as you described), or you can have two `TcpServer` with different IP/port (e.g. one on port 20000 and another on port 20001) with an outstation each. But in any case, you will need two outstations to keep track of the state of each master.

**Comment by lizapolyudova** [comment]
> or you can have two TcpServer with different IP/port (e.g. one on port 20000 and another on port 20001)

unfortunately, the upstream requirements ask that both masters use the same IP/port to communicate with the outstations. It seems like I have a working load-balancing solution in place that resolves this. Thank you for taking the time to explain this to me (relatively new to SCADA protocols).

I have a somewhat unrelated question I was hoping you could address, as well.
In upstream requirements Group32Var2 is expected to be an integer; however, the library assumes that it is a float.

https://github.com/stepfunc/dnp3/blob/f922642ac6bc8cc913afc3c944ffe6f18c13acf2/dnp3/src/app/measurement.rs#L242-L250

Is there a reason for this assumption? Would it be possible to configure this in the future? 
I am guessing the workaround is to just write the integer as a byte value to the float field.

**Comment by emgre** [comment]
Internally, we store analog values as doubles because the master might request them in any variation. Therefore, we pick the most accurate representation and do the casting just before sending it on the wire.  The group/variation concept is very DNP3 specific. You can have more details in IEEE 1815-2012 in (or around) section 4.2.

Your client probably wants you to set the default variation for the analog point events to be g32v2 (16-bit without time) in order to receive them casted as 16-bit integers when requesting a Class 1 poll. You can set the default variation through the `AnalogConfig` when adding the point to the database.

**Comment by emgre** [comment]
> I am guessing the workaround is to just write the integer as a byte value to the float field.

I'm not sure what you meant here, but just to be sure, you don't have to interpret the `f64` as a 8-byte array and cast your integer value in it. If you want to send the value 76, simply set it to `76.0`. The library will do the required casting if required when sending the data to the master. If you set it to 76.5 for example, we simply floor it down to 76 in a g32v2 (but it would be reported as 76.5 in a g32v8)

**Comment by lizapolyudova** [comment]
Ah, that's great, thank you!
