### ISSUE TITLE
Add optional delay before attempting a new connection

### ISSUE THREAD

**Issue by emgre** [stepfunc/dnp3#14]
- [x] Add an optional delay before attempting a new connection. See https://github.com/dnp3/opendnp3/issues/354
- ~Add the ability to have a custom reconnection strategy, instead of the hard-coded exponential backoff.~

**Comment by jadamcrain** [comment]
delay important for initial release, the custom strategy can wait.

**Comment by emgre** [comment]
The custom retry strategy was moved to #58.
