### ISSUE TITLE
Tags/Names for points?

### ISSUE THREAD

**Issue by Ivan-Sanchez-Diaz** [stepfunc/dnp3#140]
I have been reading the documentation and I cannot find an option that allows me to assign a tag or a name to my points in the database, does this option exist? (sorry if this is not the place to ask)

**Comment by jadamcrain** [comment]
Hi Ivan, sorry for the slow response.

DNP3 doesn't have any concept of names (only 16-bit indices). Mapping indices to tag names this is something best one outside the library.

You can reach out here with questions or email info@stepfunc.io
