### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by j-pennington** [stepfunc/dnp3#191]
Hello,

Thanks for your work on this library.  I would like to develop a java application using the java bindings on my Macbook, which I think might be supported according to the [Step Function website](https://stepfunc.io/products/libraries/dnp3/):
> Runs on all platforms and operating systems supported by the [Tokio Runtime](https://tokio.rs/): Windows, Linux, **OSX**, FreeBSD

I am able to run my java application on Debian without a problem (using 0.9.1), but when I attempt to run on OSX I encounter:
```
java.lang.UnsatisfiedLinkError: io.stepfunc.dnp3.NativeFunctions.runtime_new(Lio/stepfunc/dnp3/RuntimeConfig;)Lio/stepfunc/dnp3/Runtime;
	at io.stepfunc.dnp3.NativeFunctions.runtime_new(Native Method)
	at io.stepfunc.dnp3.Runtime.<init>(Runtime.java:37)
	at com.utilidata.service.device.comm.protocols.dnp3.Dnp3ChannelPool.<init>(Dnp3ChannelPool.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:208)
``` 
I see in the GitHub workflow file that the build and test matrices include windows and linux runners, but no macos runner.  

Is MacOS supported?  If not, will it be in the future?  Should I build from source?

Thanks,

John

**Comment by jadamcrain** [comment]
Hi @j-pennington. Our imminent 1.0.0 release will add native libraries for OSX (x64) to the JAR.

The updated docs also have instructions for building the JAR for platforms where pre-built binaries are not available.

If you can hold off a few days, I'd just wait for the 1.0.0 release JAR.

Thanks!
Adam

**Comment by emgre** [comment]
The next release (which should be released shortly) will include prebuilt MacOS x64 (Darwin) binaries. Be aware of the following caveats though:
1. This will **not** support ARM based hardware (i.e. the M1 SoC), as we had too many trouble cross-compiling it. If you have native hardware, you can build and generate the bindings yourself. [Additional documentation was written about this](https://github.com/stepfunc/dnp3/blob/c8b4c979aafef692514ab4b608bbbcfea2479b59/guide/docs/languages/build.mdx)
2. We will provide these binaries as a development tool, to allow developers to natively run their project on their local machine. However, we do not have the required hardware for proper QA of the MacOS bindings. Therefore, production environments should **not** use the MacOS bindings and should prefer the Linux or Windows binaries.

**Comment by j-pennington** [comment]
Thank you both.  Caveats understood; our use case is exactly as you describe: develop/debug natively on local machines but production runs Linux.
