### ISSUE TITLE
Configure maximum fragment size

### ISSUE THREAD

**Issue by emgre** [stepfunc/dnp3#22]
See https://github.com/dnp3/opendnp3/blob/097b6ddcb012a54c9e8e10db03fec98ddc898341/cpp/lib/include/opendnp3/master/MasterParams.h#L74-L78

**Comment by emgre** [comment]
Some relevant extracts from IEEE 1815-2012, section 4.3:

> Rule 1: DNP3 devices that are able to set their maximum transmit fragment size larger than 2048 octets shall provide the ability to limit the size (via configuration) to a maximum of 2048 octets.

> Rule 3: Outstations shall be prepared to receive fragment sizes of at least 249 octets, and masters shall be prepared to receive fragment sizes of at least 2048 octets.

> Rule 4: Master devices shall only send requests that fit within a single fragment. Any master that is capable of sending fragments larger than 249 octets shall be configurable to restrict the maximum fragment size of all requests to 249 octets.

^ We should at least check for command requests to split them if too big.

**Comment by jadamcrain** [comment]
I don't think automatic splitting is a desirable behavior. We can just fail the task with a write error to indicating to the user that the request is too big. I'd rather do that than get some undesirable result having sent the controls in multiple requests.
