### ISSUE TITLE
master file print out entire list values

### ISSUE THREAD

**Issue by yuntian1985** [stepfunc/dnp3#226]
The current c# master and outstation example only shows how to print data when outstation value changes.

 Is that possible to give an example to how to print out entire outstation values type, data from the master side directly?

**Comment by jadamcrain** [comment]
You can modify the example code to a full integrity scan instead of just an event scan:

https://github.com/stepfunc/dnp3/blob/1.1.0/ffi/bindings/dotnet/examples/master/Program.cs#L361

Change this line to:

```
var poll = channel.AddPoll(association, Request.ClassRequest(true, true, true, true), TimeSpan.FromSeconds(5));
```

This will cause all the static values to also be read every 5 seconds.
