### ISSUE TITLE
Miscellaneous master parameters (some are non-conformant)

### ISSUE THREAD

**Issue by emgre** [stepfunc/dnp3#23]
- ~~Ignore restart IIN~~
- [x] Define which classes should be requested in an event scan when detecting corresponding events available IIN
- [ ] Define the time delay before failing a non-recurring task (e.g. commands) that cannot start
- [x] Index qualifier code optimization (one-byte vs two-byte)

**Comment by jadamcrain** [comment]
We could potentially allow our Rust master to send controls/requests as one or two byte headers explicitly. Just a thought.

**Comment by jadamcrain** [comment]
Regarding the commands, I think there might be a better strategy that works for everything:

1) Limit the number of user requests that are queued, and make this number configurable. Fail tasks with a TooManyRequests `TaskError`.

2) Always ensure that tasks are failed when the communication session ends.
