### ISSUE TITLE
How to update value from master file?

### ISSUE THREAD

**Issue by lingtianyun** [stepfunc/dnp3#234]
In the outstation.cs file, value can be modified, and sent to master, like:

```
outstation.Transaction(db =>
{
    db.UpdateAnalogInput(new AnalogInput(1, ++analogValue, onlineFlags, Now()), detectEvent);
});
```
							
But is that possible to for master to modify the value and sent back to out station?

**Comment by jadamcrain** [comment]
The master doesn't modify the input values, but it can you an output value (aka control). You can receive these controls from the master in the `ControlHandler`:

https://docs.stepfunc.io/dnp3/1.1.0/guide/docs/api/outstation/controls

Each of the callback methods include a `DatabaseHandle` which can you use to modify input values *in response* to the control request.

Typically, only `BinaryOutputStatus` and `AnalogOutputStatus` values should be modified. `BinaryInput` and `AnalogInput` are really meant just to report the state of the external world, but not every device uses these types appropriately.
