### ISSUE TITLE
Incorrect documentation for iterator types that are transformed to heap lists

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/dnp3#238]
Both the Java and C# docs tell the user not to copy it. In fact, the lists is fully allocated and owned by the JVM. This is an artifact of the way the C/C++ iterators pull data right off the call stack.

https://docs.stepfunc.io/dnp3/1.2.0/java/io/stepfunc/dnp3/ReadHandler.html#handleAnalogInput(io.stepfunc.dnp3.HeaderInfo,java.util.List)

https://docs.stepfunc.io/dnp3/1.2.0/dotnet/interfacednp3_1_1IReadHandler.html#abe8bd1dbec10bd24cc11a445bd95393a

**Comment by kevinherron** [comment]
Tangential to this, the Java bindings receive a `List`, not an iterator, and the parameter name could be something better and more accurate than `it`.

**Comment by jadamcrain** [comment]
Agreed. I'll see what I can do with the code generator in the next release.

**Comment by jadamcrain** [comment]
dcca334e8e changes the docs to read:

```
void handleBinaryInput(HeaderInfo info, List<BinaryInput> values)

Handle binary input data

Parameters:
    info - Group/variation and qualifier information
    values - collection of values from the response
```

There was already a construct in our code generator to replace the special token {iterator} with a something C/C++ vs Java/.NET specific.

It's not perfect, but I'll open another ticket to improve this in the various back-ends in the next release of the generator. In the future, we can get this to read something like:

` values - List<> of values from the response`
