### ISSUE TITLE
Timestamp docs don't indicate the epoch of the value field

### ISSUE THREAD

**Issue by kevinherron** [stepfunc/dnp3#240]
`UtcTimestamp` is clear that the timestamp value is milliseconds since UNIX epoch. I assume the value in a `Timestamp` is the same, but there's no mention of it.

**Comment by kevinherron** [comment]
Tangential: I assume the library takes care of turning this timestamp into an absolute timestamp when receiving a variation that uses a timestamp relative to a prior CTO?

**Comment by jadamcrain** [comment]
Yeah, the description is weak. It's a UTC timestamp. Keeping this ticket open for next release.

Yes, the library automatically handles the CTO stuff associated with g2v3 and g4v3. It'll even gracefully handle non-sensical encodings like CTO overflows and such.
