### ISSUE TITLE
Java bindings call `System.exit` when library fails to load

### ISSUE THREAD

**Issue by kevinherron** [stepfunc/dnp3#243]
We need the failure to bubble up to the caller somehow, ideally by providing an explicit method we can call to load the library that throws on failure, rather than it being loaded during static initialization.

That aside, libraries should never call `System.exit`.

**Comment by jadamcrain** [comment]
I agree with you that there's no need to call `System.exit`. We should just let the unchecked exception bubble up out of the static initializer.

The vast majority of our users want to pretend that the native code doesn't exist, so requiring manual loading is a no go and would be a breaking change for them anyway.

How about using an environment variable to allow for manual loading instead?

**Comment by kevinherron** [comment]
I'm not sure an environment variable would be any use to us, but if you increase the visibility on `NativeFunctions` and `NativeFunctions.VERSION` I'd be happy to just do something like this:
```
try {
  System.out.println("DNP3 Library Version: " + NativeFunctions.Version);
} catch (Throwable ex) {
  // .. native library failed to load
}
```

**Comment by kevinherron** [comment]
Otherwise I can just wrap the call to `Logging.configure`, which is what is triggering initialization now, but neither approach will work until it's not exiting.

**Comment by jadamcrain** [comment]
Not sure I understand what you're saying. Are you saying that you need to disable loading of the library in the static initializer or not? I was proposing using an environment variable to disable the default static loading providing you with the opportunity to load the library on your own terms.

We can certainly provide access to the version string, but I don't see how that helps your original concern. If it's easier just to jump on a screen share we can do that too.

**Comment by jadamcrain** [comment]
> Otherwise I can just wrap the call to `Logging.configure`, which is what is triggering initialization now, but neither approach will work until it's not exiting.

Ok, I think I see now. You can put a try/catch around the first call you make into the library so long as the library doesn't call exit. Got it.

**Comment by kevinherron** [comment]
> Ok, I think I see now. You can put a try/catch around the first call you make into the library so long as the library doesn't call exit. Got it.

Yep, exactly. I don't actually need to enable/disable the static loading, I just need to know when it's going to happen so I can catch the error.

**Comment by jadamcrain** [comment]
Good. Once you've completed your initial review, I can get this and all the doc stuff into a patch release.

**Comment by kevinherron** [comment]
I've preferred explicitly loading native libraries myself in the past because not all libraries to the "right thing", but you're already doing exactly what I do manually: copy out to a temp direction and use `System.load`.

**Comment by jadamcrain** [comment]
Fixed in https://github.com/stepfunc/dnp3/commit/91ad2bca691db59bf5b3bb5c5269b99a10571d0a via https://github.com/stepfunc/oo_bindgen/pull/104
