### ISSUE TITLE
feature request: configurable local/bind address

### ISSUE THREAD

**Issue by kevinherron** [stepfunc/dnp3#245]
It's not possible to configure local/bind address of the socket that will be used to connect. This is useful to allow end users to explicitly specify which NIC in a multi-NIC server will be used to originate the connection. They don't often have the ability or even understand how they might configure network routes at the OS level to achieve this instead, and sometimes a destination is routable by multiple NICs and then they have to know how to set a priority as well...

**Comment by cyphersys** [comment]
Hello,
Just came here looking for this setting.
My physical server has several IPs assigned to NIC and also have 4 NICs.

It would be great if we could configure a local binding address in the Settings.

Thank you in advance

Regards

**Comment by jadamcrain** [comment]
OpenDNP3 had this, but this passed unnoticed through our gap analysis.

It looks like we'd call [TcpSocket::bind](https://docs.rs/tokio/1/tokio/net/struct.TcpSocket.html#method.bind) followed by [TcpSocket::connect](https://docs.rs/tokio/1/tokio/net/struct.TcpSocket.html#method.connect) in lieu of calling [TcpStream::connect](https://docs.rs/tokio/1/tokio/net/struct.TcpStream.html#method.connect) directly.

I'll need to think about the best way to add this to the 1.x release series while preserving backwards compatibility, but I don't see why we can't add this to the next release.

**Comment by jadamcrain** [comment]
@cyphersys What's your use case? Since this isn't your typical open source library on Github. I just want to make sure that you're aware of the non-commercial/production license terms. If you're interested in using the library commercially and would like to receive a quote, please reach out: `info@stepfunc.io`.

**Comment by jadamcrain** [comment]
Added in https://github.com/stepfunc/dnp3/pull/254
