### ISSUE TITLE
How can I get a same timestamp for all functions?

### ISSUE THREAD

**Issue by lingtianyun** [stepfunc/dnp3#247]
In the current master file, all values are handled by different functions separately, like:
```
HandleBinaryOutputStatus(){}
HandleAnalogOutputStatus(){}
```
Each snapshot of all the dnp3 output in a poll event is separated into different functions, but different function will yield different timestamp. How can I get a same poll id or timestamp for all functions? (Basically I want to associate each separate function with one poll event)

My possible solution:
1:

Somehow get a poll id and/or time stamp inside each function?
```

HandleBinaryOutputStatus(var poll_id, var poll_time_stamp)
{
...
}
```

2
Somehow use a master function for the above functions, so I can fill an array to all, including binary, int, float?
pseudo code like:
```
void master_function()
{
  DateTime dt = DateTime.Now;
  var binary_data = HandleBinaryOutputStatus();
  var analog_data = HandleAnalogOutputStatus();
...
}
```

Any suggestions?

**Comment by jadamcrain** [comment]
The timestamps on DNP3 events come from the source. They may or may not be valid.

If you want a common "time of reception" use [ReadHandler::BeginFragment](https://docs.stepfunc.io/dnp3/1.2.0/dotnet/interfacednp3_1_1IReadHandler.html#ad0477291569e7bca2a6a4f7872e88213) to record the time before any of HandleX methods are invoked.
