### ISSUE TITLE
Logger Callback

### ISSUE THREAD

**Issue by kevinherron** [stepfunc/dnp3#249]
It would be preferable if the log message delivered to `onMessage` did not include a pre-formatted date or the level as part of the message.

I'd rather have a callback with a signature something like: 
```
void onMessage(Instant timestamp, LogLevel level, String message);
```

where the message included _only_ the message, not the timestamp in a format out of my control or the severity. I can include these in the application log message if I decide to log it in this callback.

It might be possible to do this in a backwards-compatible manner by using Java default methods and introducing a second callback with this signature, or you might wait until an API-breaking version, or you might understandably decline all together.

**Comment by jadamcrain** [comment]
I believe that you can remove the level and timestamp from the message now using the `LoggingConfig`:

https://docs.stepfunc.io/dnp3/1.2.0/java/io/stepfunc/dnp3/LoggingConfig.html

I thinks this means that the logging framework doesn't make a system call to get the time, so you could just sample the time in Java when the call is made. The `Logger` interface already provides the level so this should satisfy your concerns? We could change the defaults in v2 to not include either by default too.

**Comment by kevinherron** [comment]
Oops, I didn't see the config. That might do everything I need.

**Comment by jadamcrain** [comment]
The defaults are on the constructor:

https://docs.stepfunc.io/dnp3/1.2.0/java/io/stepfunc/dnp3/LoggingConfig.html#%3Cinit%3E()

**Comment by kevinherron** [comment]
PEBKAC
