### ISSUE TITLE
max binary command can't exceed 16?

### ISSUE THREAD

**Issue by lingtianyun** [stepfunc/dnp3#274]
I am trying to sent from C# master file to to RTDS DNP3 Outstation some binary control signal like:

```
bool[] myList = new bool[17];//true false bool values
  
var commands = new CommandSet();
        

for (byte i = 0; i < myList.Length - 1; i++)
{
    if (myList[i])
	  commands.AddG12V1U8(i, Group12Var1.FromCode(ControlCode.FromOpType(OpType.LatchOn)));
	else
	  commands.AddG12V1U8(i, Group12Var1.FromCode(ControlCode.FromOpType(OpType.LatchOff)));

}
	
var result = await channel.Operate(association, CommandMode.DirectOperate, commands);// larger than 16 array will cause exception here
```
 
But seems I can only sent 16 binary commands, if I make a larger commandSet, the Program will throw BadStatus exception? Not sure this is a limit of master or the RTDS...

Edit:
I tried to use both c# master and out station to test, still has the same problem. 

This time, if master exceed 10, it will give a BadStatus.
```
for (byte i = 0; i < 11; i++)
{
      commands.AddG12V1U8(i, Group12Var1.FromCode(ControlCode.FromOpType(OpType.LatchOn)));
}

var result = await channel.Operate(association, CommandMode.SelectBeforeOperate, commands);//Bad Status Exception here
```
But the code does hit OutStation.
```
---- BeginFragment------
---- EndFragment------
 ```
But did not enter function OperateG12v1 at all.

I guess there a limit for the binary command in master or outstation file?

**Comment by jadamcrain** [comment]
Limit is on the RTDS side. It's common for outstations to limit the number of controls in a single request.
