### ISSUE TITLE
More details would be helpful for FileException: BadResponse

### ISSUE THREAD

**Issue by ge-jt** [stepfunc/dnp3#287]
When using the .NET ReadDirectory method with some outstations, including the 1.3.0-rc5 C# example outstation, the FileException: BadResponse will be thrown without any further details regarding what the issue is with the outstation response.

In order to help debug the issues with the outstation it would be helpful to have more details in the exception or passed in to the IAssociationInformation.TaskFail callback.

**Comment by jadamcrain** [comment]
Thanks for the request. The built-in decoder/logs will likely give you more information. Can you upload a copy of them or pcaps for the situation in question?

**Comment by ge-jt** [comment]
Thank you, I overlooked the decoder logs. That has given me much more information. I'll look over the decoder logs for now and open up a more relevant case if necessary.

**Comment by jadamcrain** [comment]
Reading a directory is an oddity in DNP3. It is implement just like a normal file read, except that the "file" data returned is in a special format. It's implement as a file read in our library, except that the data is accumulated in memory up to some limit, and then it is parsed when it is all received.

If you call `ReadDirectory` but pass it an actual file that exists on the outstation, e.g. `file.dat` the outstation will happily let you read it b/c it has no way of knowing that you actually wanted a directory... then the parsing of the directory information will fail b/c it's not in the right format.

If you do get directory information that doesn't parse correctly, please open a ticket here!

**Comment by ge-jt** [comment]
That's helpful, thanks! Also, for my clarification, does the Outstation have support for Object 70?

**Comment by jadamcrain** [comment]
@ge-jt The outstation does not yet support Group 70. This will have to wait for a future release.

The features I've added for 1.3.0 were really just to allow your organization to READ files from the outstation... sort of a minimum viable product for that subset of Group 70. That said the parser understands all of the objects now so adding the other pieces isn't a ton of work.

A complete master implementation would also need APIs to:
- Write a file to the outstation, e.g. uploading firmware
- Deleting a file from the outstation

None of these are difficult, but I wanted to deliver the features you needed as quickly as possible.

**Comment by jadamcrain** [comment]
Also, if you ever want to share anything non-publicly feel free to email me:  adam@stepfunc.io
