### ISSUE TITLE
Can't compile the .c files in bindings/c directory while using RPi4

### ISSUE THREAD

**Issue by yacoubhanna** [stepfunc/dnp3#320]
Hello, 

I tried to compile the c codes for the outstation and the master in ffi/bindings/c using my Ubuntu machine and it works. However, when I tried to compile these using my RPi4 I was getting an error while doing make. 

![dnp3-error](https://github.com/stepfunc/dnp3/assets/50341736/aaffd236-a2ce-4fb0-8c31-2f87db2ed9fe)

It seems that it is not recognizing one of the static libraries. Also, how can I make the code detect that dnp3 is locally installed instead of installing it remotely.

**Comment by yacoubhanna** [comment]
@jadamcrain I would really appreciate it if you could help me with this one. Thank you :)

**Comment by jadamcrain** [comment]
What version of RPi / OS is this on?

It looks like the linker doesn't like the aarch64 shared library from our distribution.

**Comment by yacoubhanna** [comment]
I used the command **uname -a** and it says armv7l. The OS is **Linux raspberrypi 6.1.21-v7l+**

I tried it on different RPi and got that the target architecture is not supported

**Comment by jadamcrain** [comment]
Ah, so for some reason it's trying to link the `aarch64` library in the distribution on an ARMv7 RPi...

**Comment by yacoubhanna** [comment]
I see, so If I change the CMake file to detect the ARMv7 libraries and so on will it work or I will face other issues as well?

**Comment by jadamcrain** [comment]
Yes, for some reason CMake is picking aarch64 when it should be picking armv7.

I think that is the only issue you're encountering.

**Comment by yacoubhanna** [comment]
ok, let me try to fix it. 

Thank you

**Comment by jadamcrain** [comment]
```
if(WIN32 AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|AMD64" AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(DNP3_RUST_TARGET "x86_64-pc-windows-msvc")
elseif(UNIX AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|amd64|AMD64")
    set(DNP3_RUST_TARGET "x86_64-unknown-linux-gnu")
elseif(UNIX AND CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
    set(DNP3_RUST_TARGET "aarch64-unknown-linux-gnu")
else()
    message(FATAL_ERROR "target architecture not supported by this CMake file")
endif()
```

^ This wouldn't even detect ARMv7 or ARMv6... I wonder why `CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64"` is evaluating to true however...

**Comment by jadamcrain** [comment]
@yacoubhanna Any progres son this ticket?
