### ISSUE TITLE
support for g50v4

### ISSUE THREAD

**Issue by dmabeeaveva** [stepfunc/dnp3#322]
I've been requested to request support for g50v4. It's not for a specific use so much as we used to support it when using opendnp3 (via odnp3w_set_dnptime_callback) as our api, but as we migrate to stepfunc we don't.

**Comment by jadamcrain** [comment]
hi @dmabeeaveva.

I'd be happy to add this in conjunction with a purchase order for a license.

To get a copy of our pricing and licensing/support terms, reach out to me at info@stepfunc.io

**Comment by dmabeeaveva** [comment]
Thank you. I've forwarded this to the right people.

**Comment by dmabeeaveva** [comment]
meant to chime in sooner, this request is dead.
