### ISSUE TITLE
support for partial responses

### ISSUE THREAD

**Issue by dmabeeaveva** [stepfunc/dnp3#323]
If a response contains data that the current implementation doesn't support, an error is returned and the the data that is understood is discarded. We'd like to request a mechanism to accept the partial message insofar as the current implementation can understand it.

**Comment by jadamcrain** [comment]
I'm not convinced this is a desirable feature.  Usually you'd want to configure both sides of the link during commissioning to ensure they're using objects both sides support.

It's be too easy with this option to think you have a working integration when something is actually pretty broken.

**Comment by dmabeeaveva** [comment]
fair point. if the protocol isn't structured such that chunks are 'skippable', then that's exactly what could happen. i'm mostly playing message passer here, taking dictation. as long as there's an error message returned that can be logged, imho, that should be enough to take further action by either fixing configuration or requesting enhancements.

**Comment by jadamcrain** [comment]
That's right. You can't skip an unknown object b/c DNP3 isn't tag-length-value.

For what it's worth OpenDNP3 handled unknown objects in the same manner.
