### ISSUE TITLE
v1.5.0 not on crates.io?

### ISSUE THREAD

**Issue by Tomcat-Engineering** [stepfunc/dnp3#324]
It looks like version 1.5.0 was released in September, but it doesn't show up on https://crates.io/crates/dnp3/versions.

Apologies if there is a good reason for this and I just haven't read the right documentation!

Thanks.

![image](https://github.com/stepfunc/dnp3/assets/12047075/bb455749-1f28-4fdb-91b8-896bfce3fada)

**Comment by jadamcrain** [comment]
@Tomcat-Engineering Thank you for pointing this out.

I've released 1.5.0 and made a ticket to add the crates.io publish step to CI:

https://github.com/stepfunc/dnp3/issues/325
