### ISSUE TITLE
Native libraries fail to load when `java.io.tmpdir` is relative

### ISSUE THREAD

**Issue by kevinherron** [stepfunc/dnp3#327]
Native libraries fail to load with an Exception like the following when the value of `java.io.tmpdir` is a relative path and not an absolute path:

```
java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: jre-tmp\dnp3_ffi_java15759255157366349494.dll
```

This could be fixed by ensuring `NativeFunctions.loadLibrary` always passes an absolute path to `System.load` as required:
```java
private static boolean loadLibrary(String directory, String name, String extension) throws Exception {
    try {
        java.io.InputStream stream = NativeFunctions.class.getResourceAsStream("/" + directory + "/" + name + "." + extension);
        java.nio.file.Path tempFilePath = java.nio.file.Files.createTempFile(name, "." + extension);
        tempFilePath.toFile().deleteOnExit();
        java.nio.file.Files.copy(stream, tempFilePath, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        System.load(tempFilePath.toAbsolutePath().toString()); // <-- call toAbsolutePath() first
        return true;
    } catch (Throwable e) {
        return false;
    }
}
```

**Comment by kevinherron** [comment]
Side note, it was more difficult than it should have been to track this down because the current brute force library loading logic necessarily ignores Exceptions, but it would be nice if there were some way to recover Exceptions if _none_ of the libraries were able to load or something like that.

**Comment by jadamcrain** [comment]
Do you know under what circumstances the JVM returns a relative path here?

I have a user using JVM 17 where this could be the issue:

https://github.com/stepfunc/rodbus/issues/129

**Comment by kevinherron** [comment]
In our case, it's because on certain product editions (for reasons I don't know) we explicitly set `java.io.tmpdir` to a relative path in our application config file's default values.

**Comment by jadamcrain** [comment]
1.5.1-rc1 is up for testing.

I did some work in the binding generator and it now also captures the last exception and embeds it as a cause:

https://github.com/stepfunc/oo_bindgen/pull/124

**Comment by kevinherron** [comment]
The path is absolute now but the new logic doesn't work. The first native library that fails to load short circuits the whole thing.

This part from `BindingLibraryLoader.loadTargets`:
```
            try {
                loadTargetLibrary(target);
                return;
            } catch (Exception ex) {
                lastException = ex;
            }
```

doesn't catch the `UnsatisfiedLinkError` thrown by `loadTargetLibrary`.

I think you need to catch `Throwable` instead.

**Comment by jadamcrain** [comment]
Ah, Java, and your exception inheritance hierarchy from hell.

Ez fix, brb.

**Comment by kevinherron** [comment]
Thanks, 1.5.1-rc2 fixes the issue on my machine... handing it over to QA to test the whole supported platform/edition matrix.

**Comment by kevinherron** [comment]
1.5.1-rc2 LGTM 👍

**Comment by jadamcrain** [comment]
1.5.1 has been published
