### ISSUE TITLE
Fatal error. System.AccessViolationException: dnp3.PInvoke.MasterChannelAddAssociation (Causing Application crash.)

### ISSUE THREAD

**Issue by vishuSP** [stepfunc/dnp3#334]
Hello,

we are currently using DNP3 1.5.0 .NET package for our development to be integrated with our main frame application. previously we are using the 1.2.0 version of DNP3. we have a use case where our dnp3 driver will keep on retrying to connect to device when the device simulator is down for a specific interval. 
currently in this flow we are facing an issue i.e. some fatal error directly thrown from dnp3 stack because of which application is getting crashed. 

below is the information.

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at dnp3.PInvoke.MasterChannelAddAssociation(IntPtr, UInt16, dnp3.AssociationConfigNative, dnp3.IReadHandlerNativeAdapter, dnp3.IAssociationHandlerNativeAdapter, dnp3.IAssociationInformationNativeAdapter, dnp3.AssociationIdNative ByRef)
--------------------------------
   at dnp3.MasterChannel.AddAssociation(UInt16, dnp3.AssociationConfig, dnp3.IReadHandler, dnp3.IAssociationHandler, dnp3.IAssociationInformation)

**Comment by jadamcrain** [comment]
@vishuSP:

1) Can you provide a small test case that reproduces this behavior?
2) What company do you work for? Is your company a Step Function customer with a commercial license?

**Comment by vishuSP** [comment]
hello @jadamcrain ,

To answer your 2nd question, the issue is filed on behalf of **utthunga technologies** & we have procured a commercial license from Stepfunc in 2023 if required we'll provide the exact details.

Steps to reproduce.
 we are using SCADA dnp3 simulator for our testing. 
1. we basically start our application before starting the simulator 
2. since our application is started & simulator is not, we set the device status to offline on our side.
3. we initiate a background operation in our logic where we initiate reconnection operation for a set interval & this operation will be performing until the device is up & running.
4. During this process after 30 to 40 mins our application gets crashed & as per our analysis, we found that its being triggered at MasterChannel.AddAssociation 

we basically found 2 set of errors as listed below directly thrown from DNP3 stack 

1. Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
at dnp3.PInvoke.MasterChannelAddAssociation(IntPtr, UInt16, dnp3.AssociationConfigNative, dnp3.IReadHandlerNativeAdapter, dnp3.IAssociationHandlerNativeAdapter, dnp3.IAssociationInformationNativeAdapter, dnp3.AssociationIdNative ByRef)

2. Exception occured System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at dnp3.PInvoke.MasterChannelCreateSerial(IntPtr runtime, MasterChannelConfigNative config, IntPtr path, SerialSettingsNative serial_params, UInt64 open_retry_delay, IPortStateListenerNativeAdapter listener, IntPtr& out)

**Comment by jadamcrain** [comment]
```
since our application is started & simulator is not, we set the device status to offline on our side.
we initiate a background operation in our logic where we initiate re-connection operation for a set interval & this operation will be performing until the device is up & running.
```

What's the thinking here? The master stack will continuously try to connection (with some back-off). I'm just curious why you'd want to dynamically add and remove associations and serial channels?

The stack is designed so this is possible, but there are some limitations:

1)  master_channel_add_association(..) and master_channel_add_serial(..) cannot be called from a thread owned by the stack itself (i.e. from a callback). The rust code will panic if you attempt to do so.

2) Is it possible that you're calling add_association from a callback or from a channel that has previously been shutdown?

Try to capture a full stack trace as this will tell us if this occurs from a callback or a thread solely owned by the .NET runtime.

**Comment by vishuSP** [comment]
Hello @jadamcrain 

To answer your question, we are not doing the process from any callback. 
In addition, we could find some additional stack trace as below.

Dnp3TcpChannelMaster :: Reconnect : Unable to run TCP channel for communication endpoint  127.0.0.1:20000
**thread '<unnamed>[' panicked at 'called `Option::unwrap()` on a `None` value21:18:52', D:\a\dnp3\dnp3\target\x86_64-pc-windows-msvc\release\build\dnp3-ffi-ccdd22901f1f3e69\out/runtime.rs:41:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
INF] Disconnect TCP channel master :ce37c124-a831-44d9-8b94-525039c5c33e
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at dnp3.PInvoke.RuntimeDestroy(IntPtr instance)
   at dnp3.Runtime.Shutdown()
   at uOPCSuite.DNP3TCPDriver.Dnp3TcpChannelMaster.Disconnect(Guid communicationID)
[21:18:53 FTL] [Global] [System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at dnp3.PInvoke.RuntimeDestroy(IntPtr instance)
   at dnp3.Runtime.Shutdown()
   at uOPCSuite.DNP3TCPDriver.Dnp3TcpChannelMaster.Disconnect(Guid communicationID)]

**Comment by jadamcrain** [comment]
Thanks for the stack trace. This should allow me to track down the root cause.

**Comment by jadamcrain** [comment]
@vishuSP This is the interesting part of the stack trace:

```
at dnp3.PInvoke.RuntimeDestroy(IntPtr instance)
at dnp3.Runtime.Shutdown()
at uOPCSuite.DNP3TCPDriver.Dnp3TcpChannelMaster.Disconnect(Guid communicationID)
```

It look like you're shutting down the runtime here, but this doesn't appear to be during program termination. Is it possible that you're calling `Runtime.Shutdown()` more than once?

We have guards in the code that are supposed to protect against this, however, those guards are not thread-safe.

A `Runtime` is a shared resource that all of your master channels run on. You should only need to shut this down during program termination.

**Comment by vishuSP** [comment]
hello @jadamcrain ,
Thanks for the info, we'll try changing this & see the behavior once.

**Comment by vishuSP** [comment]
@jadamcrain, if a device goes offline and comes back online after a while, we have an implementation which periodically tries to reconnect to the device. our earlier implementation was to -

- shutdown existing channel(and associated runtime) to device
- create a new channel and try to connect

Is this the right way to use the channels or should we reuse the same channel to reconnect to the device?

**Comment by jadamcrain** [comment]
@vishuSP Any luck tracking down the root cause?

**Comment by jadamcrain** [comment]
No response from submitter

**Comment by vishuSP** [comment]
@jadamcrain ,  wanted to know if there are any sample DNP3 simulators available from stepfunc for testing purpose

**Comment by jadamcrain** [comment]
@vishuSP What kind of simulation do want to do? You can use the outstation API to build and simulate an outstation.

**Comment by vishuSP** [comment]
@jadamcrain , 
- where can I find the Outstation API sample to build, can you provide the Link.?
- currently we use Freyr Scada DNP3 outstation simulation software to verify our DNP3 driver, similarly, is there any simulation software or sample code available from stepfunc which I can use for verifying.
Our Configure scenario say 50k objects (AnalogInput, BinaryInput, AnalogOutput, BinaryOutput ...) at a simulation frequency of 1second.

**Comment by jadamcrain** [comment]
You can find links to outstation example programs in the main documentation here:

https://docs.stepfunc.io/dnp3/1.5.2/guide/docs/examples/summary
