### ISSUE TITLE
unsolicited only seems to send one fragment

### ISSUE THREAD

**Issue by dmabeeaveva** [stepfunc/dnp3#340]
using 1.5.1 from c#, i set up an outstation with 50k analog points updating all of them at once, once per sec, and a master reading in unsolicited mode.
the stepfunc outstation only seems to send one fragment per sec.  about 290 pts/sec make it.

if i use an operndnp3 outstation, i get lots of fragments per second, and all point updates seem to make it through.

i'm attaching a modified version of the example code that demonstrates the problem.
[unsolrepro.zip](https://github.com/stepfunc/dnp3/files/13924138/unsolrepro.zip)

**Comment by jadamcrain** [comment]
Able to replicate in a unit test. Will get a patch release out ASAP.

**Comment by DanMabee** [comment]
thank you sir. appreciate the quick answer.

**Comment by jadamcrain** [comment]
Resolved in https://github.com/stepfunc/dnp3/pull/341

Will be included 1.5.2 patch release.

**Comment by jadamcrain** [comment]
@dmabeeaveva The 1.5.2 release is up. Please confirm that this resolves the issue.

The "no-serial" version that your company uses is currently building right now as well:

https://github.com/stepfunc/dnp3-no-serial/actions/runs/7543804025

**Comment by dmabeeaveva** [comment]
just finished testing. it's working fine now, thank you.
