### ISSUE TITLE
output file versions don't match package version

### ISSUE THREAD

**Issue by dmabeeaveva** [stepfunc/dnp3#361]
i've been asked to ask if something can be done about the version of, for example, dnp3.dll which still shows 1.0 or ffi libs that show no version information at all.

**Comment by jadamcrain** [comment]
hi @dmabeeaveva. Possibly? I believe that embedded version information is just a thing for Windows shared libraries, right?

Can you remind me which company you're with? If you don't want to share that here you send an email to `info@stepfunc.io` and I'll get back to you.

**Comment by johni-aveva** [comment]
This is from AVEVA. The metadata attributes on the .NET DLL should share the same version as the NuGet package,

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

**Comment by jadamcrain** [comment]
This was resolved in the 1.6.0 release.

**Comment by dmabeeaveva** [comment]
Thanks!
