### ISSUE TITLE
Change timeout for read operation customize in java

### ISSUE THREAD

**Issue by akash-grover-ditstek** [stepfunc/dnp3#369]
IN java when you connect a outstation you cannot change read time specifically to what you need
this cause scan integrity failed error and we also see 

no response within timeout: 5000 ms
startup integrity scan failed

Need custom property or function param to change these values

**Comment by jadamcrain** [comment]
The default timeout when creating an association is 5 seconds, but you can override it by setting the `responseTimeout` field:

https://docs.stepfunc.io/dnp3/1.6.0/java/io/stepfunc/dnp3/AssociationConfig.html#responseTimeout
