### ISSUE TITLE
Audit all log statements

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/dnp3#53]
With tracing integrated, it's worth going through each log statement in the library to determine if context in the log statement should be moved into a parent span instead.

**Comment by jadamcrain** [comment]
We can change log statements without breaking semver, so I'm removing this from the initial release project

**Comment by emgre** [comment]
Re-adding for the 1.0.0 release.

**Comment by jadamcrain** [comment]
done in 8a17583f384cbe848bae1e3ca4646a469b1ce575
