### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by emgre** [stepfunc/dnp3#57]
Add performance benchmark where a set of masters communicate with an outstation as fast as possible using [criterion](https://github.com/bheisler/criterion.rs) to collect statistics.

**Comment by jadamcrain** [comment]
I've implemented a benchmark in #64. We need to decide how we're going to track this on the CI for regressions. This action serves historical results via Github pages:

https://github.com/rhysd/github-action-benchmark

**Comment by jadamcrain** [comment]
Removing the "initial release" project tag. We can wait to do the CI part until after.
