### ISSUE TITLE
Custom retry strategy

### ISSUE THREAD

**Issue by emgre** [stepfunc/dnp3#58]
Add the ability to have a custom reconnection strategy, instead of the hard-coded exponential backoff.

**Comment by jadamcrain** [comment]
I don't believe I ever received a feature request on opendnp3 that wanted anything beyond what the exponential retry config can do.

**Comment by jadamcrain** [comment]
Most stacks probably just a fixed-delay. I can't see a use case for a custom strategy. Let's let a customer request drive this if it ever happens.
