### ISSUE TITLE
remark plugin - ability to pull in entire files outside of code blocks

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/dnp3#70]
This ability is needed to pull in the CHANGLOG.md. I prototyped how this would look with a chunk of the opendnp3 changelog,
and it looks great. It even creates links to the versions in the right sidebar!

![image](https://user-images.githubusercontent.com/305813/105410578-fe2e8780-5be6-11eb-8d56-6078b5771807.png)

**Comment by emgre** [comment]
I think you can do it with this: https://mdxjs.com/getting-started#documents

So something like this:

```
import Changelog from '../CHANGELOG.md`
<Changelog /> 
```

**Comment by jadamcrain** [comment]
It didn't like the following raw markdown:

```
### 0.9.0 ###
* :tada: first official release
```

result:

![image](https://user-images.githubusercontent.com/305813/105557821-014a7600-5cc2-11eb-8eb0-65bb6579e060.png)

**Comment by emgre** [comment]
This is caused because the `CHANGELOG.md` file is not inside the `/guide` directory, so outside the docusaurus project. I tried writing a plugin for docusaurus with the following content, but it doesn't work (it tries to resolve configuration files that do not exist) and I gave up on it.

```js
module.exports = function(ctx, options) {
    return {
        name: 'webpack-config',
        configureWebpack(config, isServer, utils) {
            var mdxConfig = config.module.rules[config.module.rules.length - 1];
            console.log(mdxConfig);
            return {
                module: {
                    rules: [
                        {
                            test: /(CHANGELOG.md)$/,
                            include: ['D:\\Desktop\\stepfunc\\dnp3'],
                            use: ['babel-loader', '@docusaurus/mdx-loader', '@docusaurus/plugin-content-pages/lib/markdownLoader'],
                        }
                    ]
                }
            }
        }
      };
}
```

The remaining solutions would be to create a symlink inside the `/guide` directory, but I'm not sure how git is going to handle it. Or, we could just link to the changelog on GitHub.

**Comment by jadamcrain** [comment]
I think linking to the changelog will be fine, so long as we can use a global version constant from the configuration to generate the link.

**Comment by emgre** [comment]
I got it working in https://github.com/stepfunc/dnp3/commit/1dec86b18a8ed2372b4e49f30f0d6ae8e5cacc0e It copies the `CHANGELOG.md` to the appropriate directory so we can import it inline. Also, I added in https://github.com/stepfunc/dnp3/commit/7aa350836e4bca913fda4970175e053f9c5382cb a JSON to contain the current version number (and other global information in the future) that we can reference from the docs. See https://github.com/stepfunc/dnp3/blob/1dec86b18a8ed2372b4e49f30f0d6ae8e5cacc0e/guide/docs/about/versioning.mdx for an example.
