### ISSUE TITLE
consider changing master ffi `Association` from class type to native struct

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/dnp3#83]
We should limit the number of class type resources in our APIs whenever possible as they have to be destroyed in C and handled specially in C#/Java.

An association is really just an address token and as far as the ffi is concerned can just be:

```
struct Association {
   address: u16
}
```

All of the methods on Association can be moved to `Master` and take an additional `Association` argument. A rust association is just a `MasterHandle` paired with an `EndpointAddress` anyway:

```
#[derive(Clone, Debug)]
pub struct AssociationHandle {
    address: EndpointAddress,
    master: MasterHandle,
}
```

This change will eliminate resource leaks related to not freeing associations. It's much easier for the user to just have to deal with freeing a master or outstation.

**Comment by emgre** [comment]
I don't think I agree with this. Here are my points:
- The `Dispose` (C#) / `close` (Java) pattern seems to model really well what we intend here. Similar to a file, if you just let it be collected by the garbage collector, we will close the connection. You should always close it manually when you really want to close it (like a file).
- Same thing in C. It makes sense to gracefully shutdown by explicitly destroying the association. Destroying a pointer makes sense here. The lifetime of the pointer represents the lifetime of the association.
- The destruction mechanism of this solution seems odd to me. We would pass a struct to the master saying "destroy this" but the struct would simply be copied?
- Making it a struct means users will be able to pass in whatever association handle they like.

**Comment by jadamcrain** [comment]
I see your point regarding it not being an opaque type anymore. I just wish that there were something like in Rust where you can have a Copyable type, but keep the inner parts private.
