### ISSUE TITLE
Logging handler cannot be set more than once

### ISSUE THREAD

**Issue by emgre** [stepfunc/dnp3#98]
Setting the log handler more than once panics with `unable to install tracing subscriber` here: https://github.com/stepfunc/dnp3/blob/83af2ee299e262167cb955074355d8a3d51de0d3/ffi/dnp3-ffi/src/logging.rs#L17-L18

The `tracing` docs of `tracing::subscriber::set_global_default` says:

> Libraries should *NOT* call `set_global_default()`! That will cause conflicts when executables try to set them later.

**Comment by jadamcrain** [comment]
we can just change this function have an error type.

**Comment by emgre** [comment]
Fixed in #109. It now returns an error if called twice.
